# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ansys.api.fluent.v0.fielddata_pb2 as fielddata__pb2


class FieldDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRange = channel.unary_unary(
                '/grpcRemoting.FieldData/GetRange',
                request_serializer=fielddata__pb2.GetRangeRequest.SerializeToString,
                response_deserializer=fielddata__pb2.GetRangeResponse.FromString,
                )
        self.GetSurfacesInfo = channel.unary_unary(
                '/grpcRemoting.FieldData/GetSurfacesInfo',
                request_serializer=fielddata__pb2.GetSurfacesInfoRequest.SerializeToString,
                response_deserializer=fielddata__pb2.GetSurfacesInfoResponse.FromString,
                )
        self.GetFieldsInfo = channel.unary_unary(
                '/grpcRemoting.FieldData/GetFieldsInfo',
                request_serializer=fielddata__pb2.GetFieldsInfoRequest.SerializeToString,
                response_deserializer=fielddata__pb2.GetFieldsInfoResponse.FromString,
                )
        self.GetSurfaces = channel.unary_stream(
                '/grpcRemoting.FieldData/GetSurfaces',
                request_serializer=fielddata__pb2.GetSurfacesRequest.SerializeToString,
                response_deserializer=fielddata__pb2.GetSurfacesResponse.FromString,
                )
        self.GetScalarField = channel.unary_stream(
                '/grpcRemoting.FieldData/GetScalarField',
                request_serializer=fielddata__pb2.GetScalarFieldRequest.SerializeToString,
                response_deserializer=fielddata__pb2.GetScalarFieldResponse.FromString,
                )
        self.GetVectorField = channel.unary_stream(
                '/grpcRemoting.FieldData/GetVectorField',
                request_serializer=fielddata__pb2.GetVectorFieldRequest.SerializeToString,
                response_deserializer=fielddata__pb2.GetVectorFieldResponse.FromString,
                )
        self.GetPathlinesField = channel.unary_stream(
                '/grpcRemoting.FieldData/GetPathlinesField',
                request_serializer=fielddata__pb2.GetPathlinesFieldRequest.SerializeToString,
                response_deserializer=fielddata__pb2.GetPathlinesFieldResponse.FromString,
                )
        self.GetParticleTracksField = channel.unary_stream(
                '/grpcRemoting.FieldData/GetParticleTracksField',
                request_serializer=fielddata__pb2.GetParticleTracksFieldRequest.SerializeToString,
                response_deserializer=fielddata__pb2.GetParticleTracksFieldResponse.FromString,
                )
        self.IsBoundaryValuesOn = channel.unary_unary(
                '/grpcRemoting.FieldData/IsBoundaryValuesOn',
                request_serializer=fielddata__pb2.IsBoundaryValuesOnRequest.SerializeToString,
                response_deserializer=fielddata__pb2.IsBoundaryValuesOnResponse.FromString,
                )


class FieldDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSurfacesInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFieldsInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSurfaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScalarField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVectorField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPathlinesField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParticleTracksField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsBoundaryValuesOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FieldDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRange,
                    request_deserializer=fielddata__pb2.GetRangeRequest.FromString,
                    response_serializer=fielddata__pb2.GetRangeResponse.SerializeToString,
            ),
            'GetSurfacesInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSurfacesInfo,
                    request_deserializer=fielddata__pb2.GetSurfacesInfoRequest.FromString,
                    response_serializer=fielddata__pb2.GetSurfacesInfoResponse.SerializeToString,
            ),
            'GetFieldsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFieldsInfo,
                    request_deserializer=fielddata__pb2.GetFieldsInfoRequest.FromString,
                    response_serializer=fielddata__pb2.GetFieldsInfoResponse.SerializeToString,
            ),
            'GetSurfaces': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSurfaces,
                    request_deserializer=fielddata__pb2.GetSurfacesRequest.FromString,
                    response_serializer=fielddata__pb2.GetSurfacesResponse.SerializeToString,
            ),
            'GetScalarField': grpc.unary_stream_rpc_method_handler(
                    servicer.GetScalarField,
                    request_deserializer=fielddata__pb2.GetScalarFieldRequest.FromString,
                    response_serializer=fielddata__pb2.GetScalarFieldResponse.SerializeToString,
            ),
            'GetVectorField': grpc.unary_stream_rpc_method_handler(
                    servicer.GetVectorField,
                    request_deserializer=fielddata__pb2.GetVectorFieldRequest.FromString,
                    response_serializer=fielddata__pb2.GetVectorFieldResponse.SerializeToString,
            ),
            'GetPathlinesField': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPathlinesField,
                    request_deserializer=fielddata__pb2.GetPathlinesFieldRequest.FromString,
                    response_serializer=fielddata__pb2.GetPathlinesFieldResponse.SerializeToString,
            ),
            'GetParticleTracksField': grpc.unary_stream_rpc_method_handler(
                    servicer.GetParticleTracksField,
                    request_deserializer=fielddata__pb2.GetParticleTracksFieldRequest.FromString,
                    response_serializer=fielddata__pb2.GetParticleTracksFieldResponse.SerializeToString,
            ),
            'IsBoundaryValuesOn': grpc.unary_unary_rpc_method_handler(
                    servicer.IsBoundaryValuesOn,
                    request_deserializer=fielddata__pb2.IsBoundaryValuesOnRequest.FromString,
                    response_serializer=fielddata__pb2.IsBoundaryValuesOnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcRemoting.FieldData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FieldData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcRemoting.FieldData/GetRange',
            fielddata__pb2.GetRangeRequest.SerializeToString,
            fielddata__pb2.GetRangeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSurfacesInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcRemoting.FieldData/GetSurfacesInfo',
            fielddata__pb2.GetSurfacesInfoRequest.SerializeToString,
            fielddata__pb2.GetSurfacesInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFieldsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcRemoting.FieldData/GetFieldsInfo',
            fielddata__pb2.GetFieldsInfoRequest.SerializeToString,
            fielddata__pb2.GetFieldsInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSurfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpcRemoting.FieldData/GetSurfaces',
            fielddata__pb2.GetSurfacesRequest.SerializeToString,
            fielddata__pb2.GetSurfacesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetScalarField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpcRemoting.FieldData/GetScalarField',
            fielddata__pb2.GetScalarFieldRequest.SerializeToString,
            fielddata__pb2.GetScalarFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVectorField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpcRemoting.FieldData/GetVectorField',
            fielddata__pb2.GetVectorFieldRequest.SerializeToString,
            fielddata__pb2.GetVectorFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPathlinesField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpcRemoting.FieldData/GetPathlinesField',
            fielddata__pb2.GetPathlinesFieldRequest.SerializeToString,
            fielddata__pb2.GetPathlinesFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetParticleTracksField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpcRemoting.FieldData/GetParticleTracksField',
            fielddata__pb2.GetParticleTracksFieldRequest.SerializeToString,
            fielddata__pb2.GetParticleTracksFieldResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsBoundaryValuesOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcRemoting.FieldData/IsBoundaryValuesOn',
            fielddata__pb2.IsBoundaryValuesOnRequest.SerializeToString,
            fielddata__pb2.IsBoundaryValuesOnResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
