# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ansys.api.fluent.v0.settings_pb2 as settings__pb2


class SettingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObjectStaticInfo = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/GetObjectStaticInfo',
                request_serializer=settings__pb2.GetObjectStaticInfoRequest.SerializeToString,
                response_deserializer=settings__pb2.GetObjectStaticInfoResponse.FromString,
                )
        self.GetVar = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/GetVar',
                request_serializer=settings__pb2.GetVarRequest.SerializeToString,
                response_deserializer=settings__pb2.GetVarResponse.FromString,
                )
        self.SetVar = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/SetVar',
                request_serializer=settings__pb2.SetVarRequest.SerializeToString,
                response_deserializer=settings__pb2.SetVarResponse.FromString,
                )
        self.Rename = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/Rename',
                request_serializer=settings__pb2.RenameRequest.SerializeToString,
                response_deserializer=settings__pb2.RenameResponse.FromString,
                )
        self.Create = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/Create',
                request_serializer=settings__pb2.CreateRequest.SerializeToString,
                response_deserializer=settings__pb2.CreateResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/Delete',
                request_serializer=settings__pb2.DeleteRequest.SerializeToString,
                response_deserializer=settings__pb2.DeleteResponse.FromString,
                )
        self.GetObjectNames = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/GetObjectNames',
                request_serializer=settings__pb2.GetObjectNamesRequest.SerializeToString,
                response_deserializer=settings__pb2.GetObjectNamesResponse.FromString,
                )
        self.GetListSize = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/GetListSize',
                request_serializer=settings__pb2.GetListSizeRequest.SerializeToString,
                response_deserializer=settings__pb2.GetListSizeResponse.FromString,
                )
        self.ResizeListObject = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/ResizeListObject',
                request_serializer=settings__pb2.ResizeListObjectRequest.SerializeToString,
                response_deserializer=settings__pb2.ResizeListObjectResponse.FromString,
                )
        self.ExecuteCommand = channel.unary_unary(
                '/ansys.api.fluent.v0.settings.Settings/ExecuteCommand',
                request_serializer=settings__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=settings__pb2.ExecuteCommandResponse.FromString,
                )


class SettingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObjectStaticInfo(self, request, context):
        """Static info about objects (type, children, commands, arguments,
        object-type) in a recursive manner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVar(self, request, context):
        """Get the value of a path 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVar(self, request, context):
        """Set the value of a path 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rename(self, request, context):
        """Rename an object 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Create a new object 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete an object 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjectNames(self, request, context):
        """Get the current list of object names 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListSize(self, request, context):
        """Get the number of elements in a list object 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeListObject(self, request, context):
        """Resize a list object 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Execute a command 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObjectStaticInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectStaticInfo,
                    request_deserializer=settings__pb2.GetObjectStaticInfoRequest.FromString,
                    response_serializer=settings__pb2.GetObjectStaticInfoResponse.SerializeToString,
            ),
            'GetVar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVar,
                    request_deserializer=settings__pb2.GetVarRequest.FromString,
                    response_serializer=settings__pb2.GetVarResponse.SerializeToString,
            ),
            'SetVar': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVar,
                    request_deserializer=settings__pb2.SetVarRequest.FromString,
                    response_serializer=settings__pb2.SetVarResponse.SerializeToString,
            ),
            'Rename': grpc.unary_unary_rpc_method_handler(
                    servicer.Rename,
                    request_deserializer=settings__pb2.RenameRequest.FromString,
                    response_serializer=settings__pb2.RenameResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=settings__pb2.CreateRequest.FromString,
                    response_serializer=settings__pb2.CreateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=settings__pb2.DeleteRequest.FromString,
                    response_serializer=settings__pb2.DeleteResponse.SerializeToString,
            ),
            'GetObjectNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectNames,
                    request_deserializer=settings__pb2.GetObjectNamesRequest.FromString,
                    response_serializer=settings__pb2.GetObjectNamesResponse.SerializeToString,
            ),
            'GetListSize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListSize,
                    request_deserializer=settings__pb2.GetListSizeRequest.FromString,
                    response_serializer=settings__pb2.GetListSizeResponse.SerializeToString,
            ),
            'ResizeListObject': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizeListObject,
                    request_deserializer=settings__pb2.ResizeListObjectRequest.FromString,
                    response_serializer=settings__pb2.ResizeListObjectResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=settings__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=settings__pb2.ExecuteCommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.fluent.v0.settings.Settings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Settings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObjectStaticInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/GetObjectStaticInfo',
            settings__pb2.GetObjectStaticInfoRequest.SerializeToString,
            settings__pb2.GetObjectStaticInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/GetVar',
            settings__pb2.GetVarRequest.SerializeToString,
            settings__pb2.GetVarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/SetVar',
            settings__pb2.SetVarRequest.SerializeToString,
            settings__pb2.SetVarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Rename(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/Rename',
            settings__pb2.RenameRequest.SerializeToString,
            settings__pb2.RenameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/Create',
            settings__pb2.CreateRequest.SerializeToString,
            settings__pb2.CreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/Delete',
            settings__pb2.DeleteRequest.SerializeToString,
            settings__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObjectNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/GetObjectNames',
            settings__pb2.GetObjectNamesRequest.SerializeToString,
            settings__pb2.GetObjectNamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetListSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/GetListSize',
            settings__pb2.GetListSizeRequest.SerializeToString,
            settings__pb2.GetListSizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResizeListObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/ResizeListObject',
            settings__pb2.ResizeListObjectRequest.SerializeToString,
            settings__pb2.ResizeListObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.settings.Settings/ExecuteCommand',
            settings__pb2.ExecuteCommandRequest.SerializeToString,
            settings__pb2.ExecuteCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
