# Lint directives.  Documentation:
# https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml
lint:
  # Linter directories to walk.
  directories:
    exclude:
      - ansys
      - codegen
      - doc
      - tests

  rules:
    # Use default rules
    all_default: true
 
    # - Proto files are not fully documented.
    # - Many repeated messages are not properly pluralized
    # - Package name is not all lower case
    # - rpc calls are not always upper camel case
    # - Field names are not always lower_snake_case
    # - Enum fields are not always UPPER_SNAKE_CASE
    # - Enum fields are not properly prefixed with the enum name
    # - Enum fields with 0 value are not suffixed UNSPECIFIED
    remove:
      - MESSAGES_HAVE_COMMENT
      - SERVICES_HAVE_COMMENT
      - RPCS_HAVE_COMMENT
      - FIELDS_HAVE_COMMENT
      - ENUMS_HAVE_COMMENT
      - ENUM_FIELDS_HAVE_COMMENT
      - FILE_HAS_COMMENT
      - REPEATED_FIELD_NAMES_PLURALIZED
      - PACKAGE_NAME_LOWER_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS

  # Linter rules option.
  rules_option:
    max_line_length:
      max_chars: 120

