# More examples and references:
# https://docs.python.org/3/howto/logging-cookbook.html
# https://docs.python.org/3/library/logging.html#logging-levels
# https://gist.github.com/kingspp/9451566a5555fb022215ca2b7b802f19

version: 1
disable_existing_loggers: no

formatters:
  console_fmt:
    format: "%(name)s %(levelname)s: %(message)s"
  logfile_fmt:
    format: "%(asctime)s %(name)-21s %(levelname)-8s %(message)s"

handlers:
  console_stdout:
    class: logging.StreamHandler
    level: ERROR
    formatter: console_fmt
    stream: ext://sys.stdout
  pyfluent_file:
    class: logging.handlers.RotatingFileHandler
    level: NOTSET #  no log level filtering on this handler, message log levels are managed by the loggers instead
    formatter: logfile_fmt
    filename: pyfluent.log
    maxBytes: 10485760 # 10 Megabytes
    backupCount: 9 # if .log file size > maxBytes, roll over to another file .log.1, then .log.2, and so on

loggers:
  pyfluent_general:
    level: WARNING
    handlers: [pyfluent_file, console_stdout]
  pyfluent_datamodel:
    level: WARNING
    handlers: [pyfluent_file, console_stdout]
  pyfluent_tui:
    level: WARNING
    handlers: [pyfluent_file, console_stdout]
  pyfluent_settings_api:
    level: WARNING
    handlers: [pyfluent_file, console_stdout]
  pyfluent_launcher:
    level: WARNING
    handlers: [pyfluent_file, console_stdout]
  pyfluent_networking:
    level: WARNING
    handlers: [pyfluent_file, console_stdout]
  pyfluent_post_objects:
    level: WARNING
    handlers: [pyfluent_file, console_stdout]
