version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  fluent.file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: pyfluent.log
    maxBytes: 10485760
    backupCount: 5
  tui.file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: tui.log
    maxBytes: 10485760
    backupCount: 5
  datamodel.file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: datamodel.log
    maxBytes: 10485760
    backupCount: 5
  settings.file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: settings_api.log
    maxBytes: 10485760
    backupCount: 5
  launcher.file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: launcher.log
    maxBytes: 10485760
    backupCount: 5
  networking.file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: networking.log
    maxBytes: 10485760
    backupCount: 5

root:
  level: INFO
  handlers: [console]
loggers:
  ansys.fluent:
    level: DEBUG
    handlers: [fluent.file]
    propagate: no
  ansys.fluent.services.datamodel:
    level: DEBUG
    handlers: [datamodel.file]
    propagate: no
  ansys.fluent.services.tui:
    level: DEBUG
    handlers: [tui.file]
    propagate: no
  ansys.fluent.services.settings_api:
    level: DEBUG
    handlers: [settings.file]
    propagate: no
  ansys.fluent.launcher:
    level: DEBUG
    handlers: [launcher.file]
    propagate: no
  ansys.fluent.networking:
    level: DEBUG
    handlers: [networking.file]
    propagate: no
  

