# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ansys.api.fluent.v0.datamodel_tui_pb2 as datamodel__tui__pb2


class DataModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyChanges = channel.unary_stream(
                '/ansys.api.fluent.v0.DataModel/NotifyChanges',
                request_serializer=datamodel__tui__pb2.NotifyChangesRequest.SerializeToString,
                response_deserializer=datamodel__tui__pb2.NotifyChangesResponse.FromString,
                )
        self.GetAttributeValue = channel.unary_unary(
                '/ansys.api.fluent.v0.DataModel/GetAttributeValue',
                request_serializer=datamodel__tui__pb2.GetAttributeValueRequest.SerializeToString,
                response_deserializer=datamodel__tui__pb2.GetAttributeValueResponse.FromString,
                )
        self.GetState = channel.unary_unary(
                '/ansys.api.fluent.v0.DataModel/GetState',
                request_serializer=datamodel__tui__pb2.GetStateRequest.SerializeToString,
                response_deserializer=datamodel__tui__pb2.GetStateResponse.FromString,
                )
        self.SetState = channel.unary_unary(
                '/ansys.api.fluent.v0.DataModel/SetState',
                request_serializer=datamodel__tui__pb2.SetStateRequest.SerializeToString,
                response_deserializer=datamodel__tui__pb2.SetStateResponse.FromString,
                )
        self.ExecuteCommand = channel.unary_unary(
                '/ansys.api.fluent.v0.DataModel/ExecuteCommand',
                request_serializer=datamodel__tui__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=datamodel__tui__pb2.ExecuteCommandResponse.FromString,
                )
        self.ExecuteQuery = channel.unary_unary(
                '/ansys.api.fluent.v0.DataModel/ExecuteQuery',
                request_serializer=datamodel__tui__pb2.ExecuteQueryRequest.SerializeToString,
                response_deserializer=datamodel__tui__pb2.ExecuteQueryResponse.FromString,
                )
        self.CompositeGet = channel.unary_unary(
                '/ansys.api.fluent.v0.DataModel/CompositeGet',
                request_serializer=datamodel__tui__pb2.CompositeGetRequest.SerializeToString,
                response_deserializer=datamodel__tui__pb2.CompositeGetResponse.FromString,
                )


class DataModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NotifyChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttributeValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompositeGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.NotifyChanges,
                    request_deserializer=datamodel__tui__pb2.NotifyChangesRequest.FromString,
                    response_serializer=datamodel__tui__pb2.NotifyChangesResponse.SerializeToString,
            ),
            'GetAttributeValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttributeValue,
                    request_deserializer=datamodel__tui__pb2.GetAttributeValueRequest.FromString,
                    response_serializer=datamodel__tui__pb2.GetAttributeValueResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=datamodel__tui__pb2.GetStateRequest.FromString,
                    response_serializer=datamodel__tui__pb2.GetStateResponse.SerializeToString,
            ),
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=datamodel__tui__pb2.SetStateRequest.FromString,
                    response_serializer=datamodel__tui__pb2.SetStateResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=datamodel__tui__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=datamodel__tui__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'ExecuteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=datamodel__tui__pb2.ExecuteQueryRequest.FromString,
                    response_serializer=datamodel__tui__pb2.ExecuteQueryResponse.SerializeToString,
            ),
            'CompositeGet': grpc.unary_unary_rpc_method_handler(
                    servicer.CompositeGet,
                    request_deserializer=datamodel__tui__pb2.CompositeGetRequest.FromString,
                    response_serializer=datamodel__tui__pb2.CompositeGetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.fluent.v0.DataModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NotifyChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ansys.api.fluent.v0.DataModel/NotifyChanges',
            datamodel__tui__pb2.NotifyChangesRequest.SerializeToString,
            datamodel__tui__pb2.NotifyChangesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAttributeValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.DataModel/GetAttributeValue',
            datamodel__tui__pb2.GetAttributeValueRequest.SerializeToString,
            datamodel__tui__pb2.GetAttributeValueResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.DataModel/GetState',
            datamodel__tui__pb2.GetStateRequest.SerializeToString,
            datamodel__tui__pb2.GetStateResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.DataModel/SetState',
            datamodel__tui__pb2.SetStateRequest.SerializeToString,
            datamodel__tui__pb2.SetStateResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.DataModel/ExecuteCommand',
            datamodel__tui__pb2.ExecuteCommandRequest.SerializeToString,
            datamodel__tui__pb2.ExecuteCommandResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.DataModel/ExecuteQuery',
            datamodel__tui__pb2.ExecuteQueryRequest.SerializeToString,
            datamodel__tui__pb2.ExecuteQueryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompositeGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ansys.api.fluent.v0.DataModel/CompositeGet',
            datamodel__tui__pb2.CompositeGetRequest.SerializeToString,
            datamodel__tui__pb2.CompositeGetResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
