# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='events.proto',
  package='grpcRemoting',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x65vents.proto\x12\x0cgrpcRemoting\"\x17\n\x15\x42\x65ginStreamingRequest\"1\n\x12TimestepEndedEvent\x12\r\n\x05index\x18\x01 \x01(\x12\x12\x0c\n\x04size\x18\x02 \x01(\x01\"$\n\x13IterationEndedEvent\x12\r\n\x05index\x18\x01 \x01(\x12\"\x1a\n\x18\x43\x61lculationsStartedEvent\"\x18\n\x16\x43\x61lculationsEndedEvent\"%\n\rCaseReadEvent\x12\x14\n\x0c\x63\x61sefilepath\x18\x01 \x01(\t\"%\n\rDataReadEvent\x12\x14\n\x0c\x64\x61tafilepath\x18\x01 \x01(\t\"\x12\n\x10InitializedEvent\"9\n\rProgressEvent\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x17\n\x0fpercentComplete\x18\x02 \x01(\x11\"\x92\x04\n\x16\x42\x65ginStreamingResponse\x12\x34\n\rcasereadevent\x18\x02 \x01(\x0b\x32\x1b.grpcRemoting.CaseReadEventH\x00\x12:\n\x10initializedevent\x18\x04 \x01(\x0b\x32\x1e.grpcRemoting.InitializedEventH\x00\x12\x34\n\rdatareadevent\x18\x06 \x01(\x0b\x32\x1b.grpcRemoting.DataReadEventH\x00\x12@\n\x13iterationendedevent\x18\x08 \x01(\x0b\x32!.grpcRemoting.IterationEndedEventH\x00\x12>\n\x12timestependedevent\x18\n \x01(\x0b\x32 .grpcRemoting.TimestepEndedEventH\x00\x12J\n\x18\x63\x61lculationsstartedevent\x18\x0b \x01(\x0b\x32&.grpcRemoting.CalculationsStartedEventH\x00\x12\x46\n\x16\x63\x61lculationsendedevent\x18\x0c \x01(\x0b\x32$.grpcRemoting.CalculationsEndedEventH\x00\x12\x34\n\rprogressevent\x18\x14 \x01(\x0b\x32\x1b.grpcRemoting.ProgressEventH\x00\x42\x04\n\x02\x61s2i\n\x06\x45vents\x12_\n\x0e\x42\x65ginStreaming\x12#.grpcRemoting.BeginStreamingRequest\x1a$.grpcRemoting.BeginStreamingResponse\"\x00\x30\x01\x62\x06proto3'
)




_BEGINSTREAMINGREQUEST = _descriptor.Descriptor(
  name='BeginStreamingRequest',
  full_name='grpcRemoting.BeginStreamingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=53,
)


_TIMESTEPENDEDEVENT = _descriptor.Descriptor(
  name='TimestepEndedEvent',
  full_name='grpcRemoting.TimestepEndedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='grpcRemoting.TimestepEndedEvent.index', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='grpcRemoting.TimestepEndedEvent.size', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=104,
)


_ITERATIONENDEDEVENT = _descriptor.Descriptor(
  name='IterationEndedEvent',
  full_name='grpcRemoting.IterationEndedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='grpcRemoting.IterationEndedEvent.index', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=142,
)


_CALCULATIONSSTARTEDEVENT = _descriptor.Descriptor(
  name='CalculationsStartedEvent',
  full_name='grpcRemoting.CalculationsStartedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=170,
)


_CALCULATIONSENDEDEVENT = _descriptor.Descriptor(
  name='CalculationsEndedEvent',
  full_name='grpcRemoting.CalculationsEndedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=196,
)


_CASEREADEVENT = _descriptor.Descriptor(
  name='CaseReadEvent',
  full_name='grpcRemoting.CaseReadEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='casefilepath', full_name='grpcRemoting.CaseReadEvent.casefilepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=235,
)


_DATAREADEVENT = _descriptor.Descriptor(
  name='DataReadEvent',
  full_name='grpcRemoting.DataReadEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='datafilepath', full_name='grpcRemoting.DataReadEvent.datafilepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=274,
)


_INITIALIZEDEVENT = _descriptor.Descriptor(
  name='InitializedEvent',
  full_name='grpcRemoting.InitializedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=294,
)


_PROGRESSEVENT = _descriptor.Descriptor(
  name='ProgressEvent',
  full_name='grpcRemoting.ProgressEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpcRemoting.ProgressEvent.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='percentComplete', full_name='grpcRemoting.ProgressEvent.percentComplete', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=353,
)


_BEGINSTREAMINGRESPONSE = _descriptor.Descriptor(
  name='BeginStreamingResponse',
  full_name='grpcRemoting.BeginStreamingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='casereadevent', full_name='grpcRemoting.BeginStreamingResponse.casereadevent', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initializedevent', full_name='grpcRemoting.BeginStreamingResponse.initializedevent', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datareadevent', full_name='grpcRemoting.BeginStreamingResponse.datareadevent', index=2,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iterationendedevent', full_name='grpcRemoting.BeginStreamingResponse.iterationendedevent', index=3,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestependedevent', full_name='grpcRemoting.BeginStreamingResponse.timestependedevent', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calculationsstartedevent', full_name='grpcRemoting.BeginStreamingResponse.calculationsstartedevent', index=5,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calculationsendedevent', full_name='grpcRemoting.BeginStreamingResponse.calculationsendedevent', index=6,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='progressevent', full_name='grpcRemoting.BeginStreamingResponse.progressevent', index=7,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='as', full_name='grpcRemoting.BeginStreamingResponse.as',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=356,
  serialized_end=886,
)

_BEGINSTREAMINGRESPONSE.fields_by_name['casereadevent'].message_type = _CASEREADEVENT
_BEGINSTREAMINGRESPONSE.fields_by_name['initializedevent'].message_type = _INITIALIZEDEVENT
_BEGINSTREAMINGRESPONSE.fields_by_name['datareadevent'].message_type = _DATAREADEVENT
_BEGINSTREAMINGRESPONSE.fields_by_name['iterationendedevent'].message_type = _ITERATIONENDEDEVENT
_BEGINSTREAMINGRESPONSE.fields_by_name['timestependedevent'].message_type = _TIMESTEPENDEDEVENT
_BEGINSTREAMINGRESPONSE.fields_by_name['calculationsstartedevent'].message_type = _CALCULATIONSSTARTEDEVENT
_BEGINSTREAMINGRESPONSE.fields_by_name['calculationsendedevent'].message_type = _CALCULATIONSENDEDEVENT
_BEGINSTREAMINGRESPONSE.fields_by_name['progressevent'].message_type = _PROGRESSEVENT
_BEGINSTREAMINGRESPONSE.oneofs_by_name['as'].fields.append(
  _BEGINSTREAMINGRESPONSE.fields_by_name['casereadevent'])
_BEGINSTREAMINGRESPONSE.fields_by_name['casereadevent'].containing_oneof = _BEGINSTREAMINGRESPONSE.oneofs_by_name['as']
_BEGINSTREAMINGRESPONSE.oneofs_by_name['as'].fields.append(
  _BEGINSTREAMINGRESPONSE.fields_by_name['initializedevent'])
_BEGINSTREAMINGRESPONSE.fields_by_name['initializedevent'].containing_oneof = _BEGINSTREAMINGRESPONSE.oneofs_by_name['as']
_BEGINSTREAMINGRESPONSE.oneofs_by_name['as'].fields.append(
  _BEGINSTREAMINGRESPONSE.fields_by_name['datareadevent'])
_BEGINSTREAMINGRESPONSE.fields_by_name['datareadevent'].containing_oneof = _BEGINSTREAMINGRESPONSE.oneofs_by_name['as']
_BEGINSTREAMINGRESPONSE.oneofs_by_name['as'].fields.append(
  _BEGINSTREAMINGRESPONSE.fields_by_name['iterationendedevent'])
_BEGINSTREAMINGRESPONSE.fields_by_name['iterationendedevent'].containing_oneof = _BEGINSTREAMINGRESPONSE.oneofs_by_name['as']
_BEGINSTREAMINGRESPONSE.oneofs_by_name['as'].fields.append(
  _BEGINSTREAMINGRESPONSE.fields_by_name['timestependedevent'])
_BEGINSTREAMINGRESPONSE.fields_by_name['timestependedevent'].containing_oneof = _BEGINSTREAMINGRESPONSE.oneofs_by_name['as']
_BEGINSTREAMINGRESPONSE.oneofs_by_name['as'].fields.append(
  _BEGINSTREAMINGRESPONSE.fields_by_name['calculationsstartedevent'])
_BEGINSTREAMINGRESPONSE.fields_by_name['calculationsstartedevent'].containing_oneof = _BEGINSTREAMINGRESPONSE.oneofs_by_name['as']
_BEGINSTREAMINGRESPONSE.oneofs_by_name['as'].fields.append(
  _BEGINSTREAMINGRESPONSE.fields_by_name['calculationsendedevent'])
_BEGINSTREAMINGRESPONSE.fields_by_name['calculationsendedevent'].containing_oneof = _BEGINSTREAMINGRESPONSE.oneofs_by_name['as']
_BEGINSTREAMINGRESPONSE.oneofs_by_name['as'].fields.append(
  _BEGINSTREAMINGRESPONSE.fields_by_name['progressevent'])
_BEGINSTREAMINGRESPONSE.fields_by_name['progressevent'].containing_oneof = _BEGINSTREAMINGRESPONSE.oneofs_by_name['as']
DESCRIPTOR.message_types_by_name['BeginStreamingRequest'] = _BEGINSTREAMINGREQUEST
DESCRIPTOR.message_types_by_name['TimestepEndedEvent'] = _TIMESTEPENDEDEVENT
DESCRIPTOR.message_types_by_name['IterationEndedEvent'] = _ITERATIONENDEDEVENT
DESCRIPTOR.message_types_by_name['CalculationsStartedEvent'] = _CALCULATIONSSTARTEDEVENT
DESCRIPTOR.message_types_by_name['CalculationsEndedEvent'] = _CALCULATIONSENDEDEVENT
DESCRIPTOR.message_types_by_name['CaseReadEvent'] = _CASEREADEVENT
DESCRIPTOR.message_types_by_name['DataReadEvent'] = _DATAREADEVENT
DESCRIPTOR.message_types_by_name['InitializedEvent'] = _INITIALIZEDEVENT
DESCRIPTOR.message_types_by_name['ProgressEvent'] = _PROGRESSEVENT
DESCRIPTOR.message_types_by_name['BeginStreamingResponse'] = _BEGINSTREAMINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BeginStreamingRequest = _reflection.GeneratedProtocolMessageType('BeginStreamingRequest', (_message.Message,), {
  'DESCRIPTOR' : _BEGINSTREAMINGREQUEST,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.BeginStreamingRequest)
  })
_sym_db.RegisterMessage(BeginStreamingRequest)

TimestepEndedEvent = _reflection.GeneratedProtocolMessageType('TimestepEndedEvent', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTEPENDEDEVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.TimestepEndedEvent)
  })
_sym_db.RegisterMessage(TimestepEndedEvent)

IterationEndedEvent = _reflection.GeneratedProtocolMessageType('IterationEndedEvent', (_message.Message,), {
  'DESCRIPTOR' : _ITERATIONENDEDEVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.IterationEndedEvent)
  })
_sym_db.RegisterMessage(IterationEndedEvent)

CalculationsStartedEvent = _reflection.GeneratedProtocolMessageType('CalculationsStartedEvent', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATIONSSTARTEDEVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.CalculationsStartedEvent)
  })
_sym_db.RegisterMessage(CalculationsStartedEvent)

CalculationsEndedEvent = _reflection.GeneratedProtocolMessageType('CalculationsEndedEvent', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATIONSENDEDEVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.CalculationsEndedEvent)
  })
_sym_db.RegisterMessage(CalculationsEndedEvent)

CaseReadEvent = _reflection.GeneratedProtocolMessageType('CaseReadEvent', (_message.Message,), {
  'DESCRIPTOR' : _CASEREADEVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.CaseReadEvent)
  })
_sym_db.RegisterMessage(CaseReadEvent)

DataReadEvent = _reflection.GeneratedProtocolMessageType('DataReadEvent', (_message.Message,), {
  'DESCRIPTOR' : _DATAREADEVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.DataReadEvent)
  })
_sym_db.RegisterMessage(DataReadEvent)

InitializedEvent = _reflection.GeneratedProtocolMessageType('InitializedEvent', (_message.Message,), {
  'DESCRIPTOR' : _INITIALIZEDEVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.InitializedEvent)
  })
_sym_db.RegisterMessage(InitializedEvent)

ProgressEvent = _reflection.GeneratedProtocolMessageType('ProgressEvent', (_message.Message,), {
  'DESCRIPTOR' : _PROGRESSEVENT,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.ProgressEvent)
  })
_sym_db.RegisterMessage(ProgressEvent)

BeginStreamingResponse = _reflection.GeneratedProtocolMessageType('BeginStreamingResponse', (_message.Message,), {
  'DESCRIPTOR' : _BEGINSTREAMINGRESPONSE,
  '__module__' : 'events_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.BeginStreamingResponse)
  })
_sym_db.RegisterMessage(BeginStreamingResponse)



_EVENTS = _descriptor.ServiceDescriptor(
  name='Events',
  full_name='grpcRemoting.Events',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=888,
  serialized_end=993,
  methods=[
  _descriptor.MethodDescriptor(
    name='BeginStreaming',
    full_name='grpcRemoting.Events.BeginStreaming',
    index=0,
    containing_service=None,
    input_type=_BEGINSTREAMINGREQUEST,
    output_type=_BEGINSTREAMINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTS)

DESCRIPTOR.services_by_name['Events'] = _EVENTS

# @@protoc_insertion_point(module_scope)
