# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='grpcRemoting',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmonitor.proto\x12\x0cgrpcRemoting\"\x14\n\x12GetMonitorsRequest\"F\n\x08UnitData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x0e\n\x06\x66\x61\x63tor\x18\x03 \x01(\x01\x12\x0e\n\x06offset\x18\x04 \x01(\x01\"\xe8\x01\n\nMonitorSet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06xlabel\x18\x03 \x01(\t\x12\x0e\n\x06ylabel\x18\x04 \x01(\t\x12\x11\n\tfrequency\x18\x05 \x01(\x12\x12\'\n\x04type\x18\x06 \x01(\x0e\x32\x19.grpcRemoting.MonitorType\x12(\n\x08unitinfo\x18\x07 \x01(\x0b\x32\x16.grpcRemoting.UnitData\x12%\n\x04\x61xis\x18\x08 \x01(\x0e\x32\x17.grpcRemoting.XAxisType\x12\x10\n\x08monitors\x18\t \x03(\t\"C\n\x13GetMonitorsResponse\x12,\n\nmonitorset\x18\x01 \x03(\x0b\x32\x18.grpcRemoting.MonitorSet\"\x12\n\x10StreamingRequest\"K\n\tXAxisData\x12*\n\txaxistype\x18\x01 \x01(\x0e\x32\x17.grpcRemoting.XAxisType\x12\x12\n\nxaxisindex\x18\x02 \x01(\x12\"*\n\x0bMonitorData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"o\n\x11StreamingResponse\x12*\n\txaxisdata\x18\x01 \x01(\x0b\x32\x17.grpcRemoting.XAxisData\x12.\n\x0byaxisvalues\x18\x02 \x03(\x0b\x32\x19.grpcRemoting.MonitorData*/\n\tXAxisType\x12\t\n\x05Unset\x10\x00\x12\r\n\tIteration\x10\x01\x12\x08\n\x04Time\x10\x02*)\n\x0bMonitorType\x12\x0c\n\x08Residual\x10\x00\x12\x0c\n\x08Solution\x10\x01\x32\xb6\x01\n\x07Monitor\x12T\n\x0bGetMonitors\x12 .grpcRemoting.GetMonitorsRequest\x1a!.grpcRemoting.GetMonitorsResponse\"\x00\x12U\n\x0e\x42\x65ginStreaming\x12\x1e.grpcRemoting.StreamingRequest\x1a\x1f.grpcRemoting.StreamingResponse\"\x00\x30\x01\x62\x06proto3'
)

_XAXISTYPE = _descriptor.EnumDescriptor(
  name='XAxisType',
  full_name='grpcRemoting.XAxisType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unset', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Iteration', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Time', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=683,
  serialized_end=730,
)
_sym_db.RegisterEnumDescriptor(_XAXISTYPE)

XAxisType = enum_type_wrapper.EnumTypeWrapper(_XAXISTYPE)
_MONITORTYPE = _descriptor.EnumDescriptor(
  name='MonitorType',
  full_name='grpcRemoting.MonitorType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Residual', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Solution', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=732,
  serialized_end=773,
)
_sym_db.RegisterEnumDescriptor(_MONITORTYPE)

MonitorType = enum_type_wrapper.EnumTypeWrapper(_MONITORTYPE)
Unset = 0
Iteration = 1
Time = 2
Residual = 0
Solution = 1



_GETMONITORSREQUEST = _descriptor.Descriptor(
  name='GetMonitorsRequest',
  full_name='grpcRemoting.GetMonitorsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=51,
)


_UNITDATA = _descriptor.Descriptor(
  name='UnitData',
  full_name='grpcRemoting.UnitData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpcRemoting.UnitData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='grpcRemoting.UnitData.unit', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='factor', full_name='grpcRemoting.UnitData.factor', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='grpcRemoting.UnitData.offset', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=123,
)


_MONITORSET = _descriptor.Descriptor(
  name='MonitorSet',
  full_name='grpcRemoting.MonitorSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpcRemoting.MonitorSet.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='grpcRemoting.MonitorSet.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xlabel', full_name='grpcRemoting.MonitorSet.xlabel', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ylabel', full_name='grpcRemoting.MonitorSet.ylabel', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='grpcRemoting.MonitorSet.frequency', index=4,
      number=5, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='grpcRemoting.MonitorSet.type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unitinfo', full_name='grpcRemoting.MonitorSet.unitinfo', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='axis', full_name='grpcRemoting.MonitorSet.axis', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='monitors', full_name='grpcRemoting.MonitorSet.monitors', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=358,
)


_GETMONITORSRESPONSE = _descriptor.Descriptor(
  name='GetMonitorsResponse',
  full_name='grpcRemoting.GetMonitorsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='monitorset', full_name='grpcRemoting.GetMonitorsResponse.monitorset', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=427,
)


_STREAMINGREQUEST = _descriptor.Descriptor(
  name='StreamingRequest',
  full_name='grpcRemoting.StreamingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=447,
)


_XAXISDATA = _descriptor.Descriptor(
  name='XAxisData',
  full_name='grpcRemoting.XAxisData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xaxistype', full_name='grpcRemoting.XAxisData.xaxistype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xaxisindex', full_name='grpcRemoting.XAxisData.xaxisindex', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=524,
)


_MONITORDATA = _descriptor.Descriptor(
  name='MonitorData',
  full_name='grpcRemoting.MonitorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grpcRemoting.MonitorData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='grpcRemoting.MonitorData.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=568,
)


_STREAMINGRESPONSE = _descriptor.Descriptor(
  name='StreamingResponse',
  full_name='grpcRemoting.StreamingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xaxisdata', full_name='grpcRemoting.StreamingResponse.xaxisdata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yaxisvalues', full_name='grpcRemoting.StreamingResponse.yaxisvalues', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=681,
)

_MONITORSET.fields_by_name['type'].enum_type = _MONITORTYPE
_MONITORSET.fields_by_name['unitinfo'].message_type = _UNITDATA
_MONITORSET.fields_by_name['axis'].enum_type = _XAXISTYPE
_GETMONITORSRESPONSE.fields_by_name['monitorset'].message_type = _MONITORSET
_XAXISDATA.fields_by_name['xaxistype'].enum_type = _XAXISTYPE
_STREAMINGRESPONSE.fields_by_name['xaxisdata'].message_type = _XAXISDATA
_STREAMINGRESPONSE.fields_by_name['yaxisvalues'].message_type = _MONITORDATA
DESCRIPTOR.message_types_by_name['GetMonitorsRequest'] = _GETMONITORSREQUEST
DESCRIPTOR.message_types_by_name['UnitData'] = _UNITDATA
DESCRIPTOR.message_types_by_name['MonitorSet'] = _MONITORSET
DESCRIPTOR.message_types_by_name['GetMonitorsResponse'] = _GETMONITORSRESPONSE
DESCRIPTOR.message_types_by_name['StreamingRequest'] = _STREAMINGREQUEST
DESCRIPTOR.message_types_by_name['XAxisData'] = _XAXISDATA
DESCRIPTOR.message_types_by_name['MonitorData'] = _MONITORDATA
DESCRIPTOR.message_types_by_name['StreamingResponse'] = _STREAMINGRESPONSE
DESCRIPTOR.enum_types_by_name['XAxisType'] = _XAXISTYPE
DESCRIPTOR.enum_types_by_name['MonitorType'] = _MONITORTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMonitorsRequest = _reflection.GeneratedProtocolMessageType('GetMonitorsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMONITORSREQUEST,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.GetMonitorsRequest)
  })
_sym_db.RegisterMessage(GetMonitorsRequest)

UnitData = _reflection.GeneratedProtocolMessageType('UnitData', (_message.Message,), {
  'DESCRIPTOR' : _UNITDATA,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.UnitData)
  })
_sym_db.RegisterMessage(UnitData)

MonitorSet = _reflection.GeneratedProtocolMessageType('MonitorSet', (_message.Message,), {
  'DESCRIPTOR' : _MONITORSET,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.MonitorSet)
  })
_sym_db.RegisterMessage(MonitorSet)

GetMonitorsResponse = _reflection.GeneratedProtocolMessageType('GetMonitorsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETMONITORSRESPONSE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.GetMonitorsResponse)
  })
_sym_db.RegisterMessage(GetMonitorsResponse)

StreamingRequest = _reflection.GeneratedProtocolMessageType('StreamingRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGREQUEST,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.StreamingRequest)
  })
_sym_db.RegisterMessage(StreamingRequest)

XAxisData = _reflection.GeneratedProtocolMessageType('XAxisData', (_message.Message,), {
  'DESCRIPTOR' : _XAXISDATA,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.XAxisData)
  })
_sym_db.RegisterMessage(XAxisData)

MonitorData = _reflection.GeneratedProtocolMessageType('MonitorData', (_message.Message,), {
  'DESCRIPTOR' : _MONITORDATA,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.MonitorData)
  })
_sym_db.RegisterMessage(MonitorData)

StreamingResponse = _reflection.GeneratedProtocolMessageType('StreamingResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGRESPONSE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:grpcRemoting.StreamingResponse)
  })
_sym_db.RegisterMessage(StreamingResponse)



_MONITOR = _descriptor.ServiceDescriptor(
  name='Monitor',
  full_name='grpcRemoting.Monitor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=776,
  serialized_end=958,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMonitors',
    full_name='grpcRemoting.Monitor.GetMonitors',
    index=0,
    containing_service=None,
    input_type=_GETMONITORSREQUEST,
    output_type=_GETMONITORSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BeginStreaming',
    full_name='grpcRemoting.Monitor.BeginStreaming',
    index=1,
    containing_service=None,
    input_type=_STREAMINGREQUEST,
    output_type=_STREAMINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITOR)

DESCRIPTOR.services_by_name['Monitor'] = _MONITOR

# @@protoc_insertion_point(module_scope)
