"""Data for for builtin setting classes."""

from ansys.fluent.core import FluentVersion

# {<class name>: (<kind>, <path>)}
DATA = {
    "Setup": ("Singleton", "setup"),
    "General": ("Singleton", "setup.general"),
    "Models": ("Singleton", "setup.models"),
    "Multiphase": ("Singleton", "setup.models.multiphase"),
    "Energy": ("Singleton", "setup.models.energy"),
    "Viscous": ("Singleton", "setup.models.viscous"),
    "Radiation": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.radiation",
            FluentVersion.v242: "setup.models.radiation",
            FluentVersion.v241: "setup.models.radiation",
            FluentVersion.v232: "setup.models.radiation",
        },
    ),
    "Species": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.species",
            FluentVersion.v242: "setup.models.species",
            FluentVersion.v241: "setup.models.species",
            FluentVersion.v232: "setup.models.species",
        },
    ),
    "DiscretePhase": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.discrete_phase",
            FluentVersion.v242: "setup.models.discrete_phase",
            FluentVersion.v241: "setup.models.discrete_phase",
            FluentVersion.v232: "setup.models.discrete_phase",
            FluentVersion.v231: "setup.models.discrete_phase",
        },
    ),
    "Injections": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.discrete_phase.injections",
            FluentVersion.v242: "setup.models.discrete_phase.injections",
            FluentVersion.v241: "setup.models.discrete_phase.injections",
            FluentVersion.v232: "setup.models.discrete_phase.injections",
            FluentVersion.v231: "setup.models.discrete_phase.injections",
        },
    ),
    "Injection": (
        "NamedObject",
        {
            FluentVersion.v251: "setup.models.discrete_phase.injections",
            FluentVersion.v242: "setup.models.discrete_phase.injections",
            FluentVersion.v241: "setup.models.discrete_phase.injections",
            FluentVersion.v232: "setup.models.discrete_phase.injections",
            FluentVersion.v231: "setup.models.discrete_phase.injections",
        },
    ),
    "VirtualBladeModel": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.virtual_blade_model",
            FluentVersion.v242: "setup.models.virtual_blade_model",
            FluentVersion.v241: "setup.models.virtual_blade_model",
            FluentVersion.v232: "setup.models.virtual_blade_model",
            FluentVersion.v231: "setup.models.virtual_blade_model",
        },
    ),
    "Optics": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.optics",
            FluentVersion.v242: "setup.models.optics",
            FluentVersion.v241: "setup.models.optics",
            FluentVersion.v232: "setup.models.optics",
            FluentVersion.v231: "setup.models.optics",
        },
    ),
    "Structure": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.structure",
            FluentVersion.v242: "setup.models.structure",
            FluentVersion.v241: "setup.models.structure",
            FluentVersion.v232: "setup.models.structure",
        },
    ),
    "Ablation": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.ablation",
            FluentVersion.v242: "setup.models.ablation",
            FluentVersion.v241: "setup.models.ablation",
            FluentVersion.v232: "setup.models.ablation",
        },
    ),
    "EChemistry": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.echemistry",
            FluentVersion.v242: "setup.models.echemistry",
            FluentVersion.v241: "setup.models.echemistry",
        },
    ),
    "Battery": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.battery",
            FluentVersion.v242: "setup.models.battery",
            FluentVersion.v241: "setup.models.battery",
        },
    ),
    "SystemCoupling": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.system_coupling",
            FluentVersion.v242: "setup.models.system_coupling",
            FluentVersion.v241: "setup.models.system_coupling",
        },
    ),
    "Sofc": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.sofc",
            FluentVersion.v242: "setup.models.sofc",
            FluentVersion.v241: "setup.models.sofc",
        },
    ),
    "Pemfc": (
        "Singleton",
        {
            FluentVersion.v251: "setup.models.pemfc",
            FluentVersion.v242: "setup.models.pemfc",
        },
    ),
    "Materials": ("Singleton", "setup.materials"),
    "FluidMaterials": ("Singleton", "setup.materials.fluid"),
    "FluidMaterial": ("NamedObject", "setup.materials.fluid"),
    "SolidMaterials": ("Singleton", "setup.materials.solid"),
    "SolidMaterial": ("NamedObject", "setup.materials.solid"),
    "MixtureMaterials": ("Singleton", "setup.materials.mixture"),
    "MixtureMaterial": ("NamedObject", "setup.materials.mixture"),
    "ParticleMixtureMaterials": ("Singleton", "setup.materials.particle_mixture"),
    "ParticleMixtureMaterial": ("NamedObject", "setup.materials.particle_mixture"),
    "CellZoneConditions": ("Singleton", "setup.cell_zone_conditions"),
    "CellZoneCondition": (
        "NamedObject",
        {
            FluentVersion.v251: "setup.cell_zone_conditions",
            FluentVersion.v242: "setup.cell_zone_conditions",
            FluentVersion.v241: "setup.cell_zone_conditions",
            FluentVersion.v232: "setup.cell_zone_conditions",
            FluentVersion.v231: "setup.cell_zone_conditions",
        },
    ),
    "FluidCellZones": ("Singleton", "setup.cell_zone_conditions.fluid"),
    "FluidCellZone": ("NamedObject", "setup.cell_zone_conditions.fluid"),
    "SolidCellZones": ("Singleton", "setup.cell_zone_conditions.solid"),
    "SolidCellZone": ("NamedObject", "setup.cell_zone_conditions.solid"),
    "BoundaryConditions": ("Singleton", "setup.boundary_conditions"),
    "BoundaryCondition": (
        "NamedObject",
        {
            FluentVersion.v251: "setup.boundary_conditions",
            FluentVersion.v242: "setup.boundary_conditions",
            FluentVersion.v241: "setup.boundary_conditions",
            FluentVersion.v232: "setup.boundary_conditions",
            FluentVersion.v231: "setup.boundary_conditions",
        },
    ),
    "AxisBoundaries": ("Singleton", "setup.boundary_conditions.axis"),
    "AxisBoundary": ("NamedObject", "setup.boundary_conditions.axis"),
    "DegassingBoundaries": ("Singleton", "setup.boundary_conditions.degassing"),
    "DegassingBoundary": ("NamedObject", "setup.boundary_conditions.degassing"),
    "ExhaustFanBoundaries": ("Singleton", "setup.boundary_conditions.exhaust_fan"),
    "ExhaustFanBoundary": ("NamedObject", "setup.boundary_conditions.exhaust_fan"),
    "FanBoundaries": ("Singleton", "setup.boundary_conditions.fan"),
    "FanBoundary": ("NamedObject", "setup.boundary_conditions.fan"),
    "GeometryBoundaries": ("Singleton", "setup.boundary_conditions.geometry"),
    "GeometryBoundary": ("NamedObject", "setup.boundary_conditions.geometry"),
    "InletVentBoundaries": ("Singleton", "setup.boundary_conditions.inlet_vent"),
    "InletVentBoundary": ("NamedObject", "setup.boundary_conditions.inlet_vent"),
    "IntakeFanBoundaries": ("Singleton", "setup.boundary_conditions.intake_fan"),
    "IntakeFanBoundary": ("NamedObject", "setup.boundary_conditions.intake_fan"),
    "InterfaceBoundaries": ("Singleton", "setup.boundary_conditions.interface"),
    "InterfaceBoundary": ("NamedObject", "setup.boundary_conditions.interface"),
    "InteriorBoundaries": ("Singleton", "setup.boundary_conditions.interior"),
    "InteriorBoundary": ("NamedObject", "setup.boundary_conditions.interior"),
    "MassFlowInlets": ("Singleton", "setup.boundary_conditions.mass_flow_inlet"),
    "MassFlowInlet": ("NamedObject", "setup.boundary_conditions.mass_flow_inlet"),
    "MassFlowOutlets": ("Singleton", "setup.boundary_conditions.mass_flow_outlet"),
    "MassFlowOutlet": ("NamedObject", "setup.boundary_conditions.mass_flow_outlet"),
    "NetworkBoundaries": ("Singleton", "setup.boundary_conditions.network"),
    "NetworkBoundary": ("NamedObject", "setup.boundary_conditions.network"),
    "NetworkEndBoundaries": ("Singleton", "setup.boundary_conditions.network_end"),
    "NetworkEndBoundary": ("NamedObject", "setup.boundary_conditions.network_end"),
    "OutflowBoundaries": ("Singleton", "setup.boundary_conditions.outflow"),
    "OutflowBoundary": ("NamedObject", "setup.boundary_conditions.outflow"),
    "OutletVentBoundaries": ("Singleton", "setup.boundary_conditions.outlet_vent"),
    "OutletVentBoundary": ("NamedObject", "setup.boundary_conditions.outlet_vent"),
    "OversetBoundaries": ("Singleton", "setup.boundary_conditions.overset"),
    "OversetBoundary": ("NamedObject", "setup.boundary_conditions.overset"),
    "PeriodicBoundaries": ("Singleton", "setup.boundary_conditions.periodic"),
    "PeriodicBoundary": ("NamedObject", "setup.boundary_conditions.periodic"),
    "PorousJumpBoundaries": ("Singleton", "setup.boundary_conditions.porous_jump"),
    "PorousJumpBoundary": ("NamedObject", "setup.boundary_conditions.porous_jump"),
    "PressureFarFieldBoundaries": (
        "Singleton",
        "setup.boundary_conditions.pressure_far_field",
    ),
    "PressureFarFieldBoundary": (
        "NamedObject",
        "setup.boundary_conditions.pressure_far_field",
    ),
    "PressureInlets": ("Singleton", "setup.boundary_conditions.pressure_inlet"),
    "PressureInlet": ("NamedObject", "setup.boundary_conditions.pressure_inlet"),
    "PressureOutlets": ("Singleton", "setup.boundary_conditions.pressure_outlet"),
    "PressureOutlet": ("NamedObject", "setup.boundary_conditions.pressure_outlet"),
    "RadiatorBoundaries": ("Singleton", "setup.boundary_conditions.radiator"),
    "RadiatorBoundary": ("NamedObject", "setup.boundary_conditions.radiator"),
    "RansLesInterfaceBoundaries": (
        "Singleton",
        "setup.boundary_conditions.rans_les_interface",
    ),
    "RansLesInterfaceBoundary": (
        "NamedObject",
        "setup.boundary_conditions.rans_les_interface",
    ),
    "RecirculationInlets": (
        "Singleton",
        "setup.boundary_conditions.recirculation_inlet",
    ),
    "RecirculationInlet": (
        "NamedObject",
        "setup.boundary_conditions.recirculation_inlet",
    ),
    "RecirculationOutlets": (
        "Singleton",
        "setup.boundary_conditions.recirculation_outlet",
    ),
    "RecirculationOutlet": (
        "NamedObject",
        "setup.boundary_conditions.recirculation_outlet",
    ),
    "ShadowBoundaries": ("Singleton", "setup.boundary_conditions.shadow"),
    "ShadowBoundary": ("NamedObject", "setup.boundary_conditions.shadow"),
    "SymmetryBoundaries": ("Singleton", "setup.boundary_conditions.symmetry"),
    "SymmetryBoundary": ("NamedObject", "setup.boundary_conditions.symmetry"),
    "VelocityInlets": ("Singleton", "setup.boundary_conditions.velocity_inlet"),
    "VelocityInlet": ("NamedObject", "setup.boundary_conditions.velocity_inlet"),
    "WallBoundaries": ("Singleton", "setup.boundary_conditions.wall"),
    "WallBoundary": ("NamedObject", "setup.boundary_conditions.wall"),
    "NonReflectingBoundaries": (
        "Singleton",
        "setup.boundary_conditions.non_reflecting_bc",
    ),
    "NonReflectingBoundary": (
        "NamedObject",
        "setup.boundary_conditions.non_reflecting_bc",
    ),
    "PerforatedWallBoundaries": (
        "Singleton",
        "setup.boundary_conditions.perforated_wall",
    ),
    "PerforatedWallBoundary": (
        "NamedObject",
        "setup.boundary_conditions.perforated_wall",
    ),
    "MeshInterfaces": (
        "Singleton",
        {
            FluentVersion.v251: "setup.mesh_interfaces",
            FluentVersion.v242: "setup.mesh_interfaces",
            FluentVersion.v241: "setup.mesh_interfaces",
            FluentVersion.v232: "setup.mesh_interfaces",
        },
    ),
    "DynamicMesh": ("Singleton", {FluentVersion.v251: "setup.dynamic_mesh"}),
    "ReferenceValues": ("Singleton", "setup.reference_values"),
    "ReferenceFrames": (
        "Singleton",
        {
            FluentVersion.v251: "setup.reference_frames",
            FluentVersion.v242: "setup.reference_frames",
            FluentVersion.v241: "setup.reference_frames",
            FluentVersion.v232: "setup.reference_frames",
        },
    ),
    "ReferenceFrame": (
        "NamedObject",
        {
            FluentVersion.v251: "setup.reference_frames",
            FluentVersion.v242: "setup.reference_frames",
            FluentVersion.v241: "setup.reference_frames",
            FluentVersion.v232: "setup.reference_frames",
        },
    ),
    "NamedExpressions": (
        "Singleton",
        {
            FluentVersion.v251: "setup.named_expressions",
            FluentVersion.v242: "setup.named_expressions",
            FluentVersion.v241: "setup.named_expressions",
            FluentVersion.v232: "setup.named_expressions",
        },
    ),
    "NamedExpression": (
        "NamedObject",
        {
            FluentVersion.v251: "setup.named_expressions",
            FluentVersion.v242: "setup.named_expressions",
            FluentVersion.v241: "setup.named_expressions",
            FluentVersion.v232: "setup.named_expressions",
        },
    ),
    "Methods": ("Singleton", "solution.methods"),
    "Controls": ("Singleton", "solution.controls"),
    "ReportDefinitions": ("Singleton", "solution.report_definitions"),
    "Monitor": ("Singleton", "solution.monitor"),
    "Residual": ("Singleton", "solution.monitor.residual"),
    "ReportFiles": ("Singleton", "solution.monitor.report_files"),
    "ReportFile": ("NamedObject", "solution.monitor.report_files"),
    "ReportPlots": ("Singleton", "solution.monitor.report_plots"),
    "ReportPlot": ("NamedObject", "solution.monitor.report_plots"),
    "ConvergenceConditions": ("Singleton", "solution.monitor.convergence_conditions"),
    "CellRegisters": ("Singleton", "solution.cell_registers"),
    "CellRegister": ("NamedObject", "solution.cell_registers"),
    "Initialization": ("Singleton", "solution.initialization"),
    "CalculationActivity": ("Singleton", "solution.calculation_activity"),
    "ExecuteCommands": ("Singleton", "solution.calculation_activity.execute_commands"),
    "CaseModification": (
        "Singleton",
        "solution.calculation_activity.case_modification",
    ),
    "RunCalculation": ("Singleton", "solution.run_calculation"),
}
