name: Doc Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "!*dev*"

permissions:
  contents: read
  packages: read
  pull-requests: read
  issues: read

env:
  DOCUMENTATION_CNAME: "fluent.docs.pyansys.com"
  DOC_DEPLOYMENT_IMAGE_TAG: v25.2.0
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  PYFLUENT_TIMEOUT_FORCE_EXIT: 30
  PYFLUENT_LAUNCH_CONTAINER: 1
  PYFLUENT_LOGGING: "DEBUG"
  PYFLUENT_WATCHDOG_DEBUG: "OFF"
  PYFLUENT_HIDE_LOG_SECRETS: 1
  PYFLUENT_SKIP_API_UPGRADE_ADVICE: 1
  PYFLUENT_CONTAINER_MOUNT_SOURCE: "/home/ansys/Downloads/ansys_fluent_core_examples"

jobs:
  build_release_docs:
    name: "Build Release Documentation"
    runs-on: [self-hosted, pyfluent]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.11"

      - name: Install OS packages
        run: |
          sudo apt update
          sudo apt-get install pandoc libegl1 make xvfb libfontconfig1 libxrender1 libxkbcommon-x11-0 -y

      - name: Install pyfluent
        run: make install

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ansys-bot
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Fluent docker image
        run: make docker-pull
        env:
          FLUENT_IMAGE_TAG: ${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}

      - name: Run API codegen
        run: make api-codegen
        env:
          FLUENT_IMAGE_TAG: ${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}

      - name: Build All Documentation
        run: |
          pip install -r requirements/requirements_build.txt
          pip install ansys-fluent-core[docs]
          make build-all-docs
        env:
          FLUENT_IMAGE_TAG: ${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}
          BUILD_ALL_DOCS: 1

      - name: Zip HTML Documentation before upload
        env:
          DOC_DEPLOYMENT_IMG: ${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}
        run: |
          sudo apt install zip -y
          pushd doc/_build/html
          zip -r ../../../HTML-Documentation-tag-${DOC_DEPLOYMENT_IMG}.zip .
          popd

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: HTML-Documentation-tag-${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}
          path: HTML-Documentation-tag-${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}.zip
          retention-days: 7

      - name: Remove all docker images
        if: always()
        run: make docker-clean-images

  deploy_release_docs:
    name: "Deploy Release Documentation"
    runs-on: ubuntu-latest
    needs: [build_release_docs]
    steps:
      - name: "Deploy release documentation"
        uses: ansys/actions/doc-deploy-stable@v10.1
        with:
          doc-artifact-name: "HTML-Documentation-tag-${{ env.DOC_DEPLOYMENT_IMAGE_TAG }}"
          decompress-artifact: true
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
