name: Force update stable Fluent image version

on:
  #pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # Required for actions/checkout and repository reads.
  packages: read # Required for docker/login-action access to GHCR images.

env:
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  MAIN_PYTHON_VERSION: "3.12"
  FLUENT_IMAGE_TAG: v27.1.latest
  FLUENT_VERSION: 271

jobs:
  test:
    name: Update latest Fluent image
    runs-on: [self-hosted, pyfluent]
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ansys-bot
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Fluent docker image
        run: make docker-pull
        env:
          FLUENT_IMAGE_TAG: ${{ env.FLUENT_IMAGE_TAG }}

      - name: Update Fluent image
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
          IMAGE_TAG: ${{ env.FLUENT_IMAGE_TAG }}
        if: github.ref == 'refs/heads/main'
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/ansys/fluent:${IMAGE_TAG} | sed 's/.*@//')
          gh variable set FLUENT_STABLE_IMAGE_DEV --body $DIGEST
