
name: Run Custom Tests

on:
  #pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
  PYFLUENT_TIMEOUT_FORCE_EXIT: 5
  PYFLUENT_LAUNCH_CONTAINER: 1

jobs:

  build_test:
    name: Build and Test
    runs-on: [self-hosted, pyfluent]
    strategy:
      fail-fast: false
      matrix:
        include:
          - image-tag: v22.2.0
            version: 222
          - image-tag: v23.1.0
            version: 231
          - image-tag: v23.2.0
            version: 232
          - image-tag: v24.1.0
            version: 241

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: Python-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements/requirements_*.txt') }}
          restore-keys: |
            Python-${{ runner.os }}-${{ matrix.python-version }}

      - name: Add version information
        run: make version-info

      - name: Install pyfluent
        run: make install

      - name: Retrieve PyFluent version
        run: |
          echo "PYFLUENT_VERSION=$(python -c "from ansys.fluent.core import __version__; print(); print(__version__)" | tail -1)" >> $GITHUB_OUTPUT
          echo "PYFLUENT version is: $(python -c "from ansys.fluent.core import __version__; print(); print(__version__)" | tail -1)"
        id: version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.REPO_DOWNLOAD_PAT }}

      - name: Pull Fluent docker image
        run: make docker-pull
        env:
          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}

      - name: Run API codegen
        run: make api-codegen
        env:
          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}

      - name: Print Fluent version info
        run: |
          cat src/ansys/fluent/core/fluent_version_${{ matrix.version }}.py

      - name: Install again after codegen
        run: |
          rm -rf dist
          make install > /dev/null

      - name: Unit Testing
        run: make unittest-custom
        env:
          FLUENT_IMAGE_TAG: ${{ matrix.image-tag }}
